### ISSUE TITLE
🐛 [Bug] Grid 컴포넌트 rows columns 무시

### ISSUE THREAD

**Issue by aLVINlEE9** [GhostPangPang/GhostPong#142]
### Problem

Grid component에 rows 와 columns를 명시해줘도 rowsSize와 columnsSize를 기준으로 grid가 만들어집니다

### Reproduction

```typescript
<Grid container="grid" rows={4} columns={5} rowsSize={[1, 2, 3, 4, 5]} columnsSize={[1, 1, 1]}>
</Grid>
```

### Screenshot

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/74805318/234468763-d6bb4f6b-85c6-4f90-ab79-3c2cad7065ef.png">

**Comment by nyeoni** [comment]
이 부분을 고치려 하였으나 잘 되지 않아 같이 해결해보면 좋을 것 같아요!
1. 타입에러 발생시키기
- 타입스크립트를 통해 columns 의 값을 갖는 columnsSize 에 대한 타입을 만들어보려고 하였지만, 잘 되지 않아 더 생각해봐야할 것 같습니다. 혹시 더 좋을 방법 있으면 알려주세요.

2. throw Error 발생시키기
- throw Error 로 styled 안에서 처리를 하게 되면 런타임때 발생되는 에러이므로 별로 좋지 않다는 생각을 하였어요. 그래서 커스텀으로 컴파일 에러를 발생시키는 방법이 있나 찾아보았지만 현재 제가 찾아본 바로는 할 수 없었습니다. 

같이 더 고민해보면 좋을 것 같아요 @aLVINlEE9
