### ISSUE TITLE
✨ [Feature] 유저 게임 히스토리 가져오기 api 수정 요청

### ISSUE THREAD

**Issue by aLVINlEE9** [GhostPangPang/GhostPong#168]
### Description

endpoint: `/user/{userId}/history?cursor=0` 0으로 요청보내면 전체 히스토리 수를 추가해서 보내주세요. 편하신 `key`와 `type`을  comment에 적어주세요

이유: 히스토리 페이지네이션을 할때 전체 history 수를 알아야지 마지막 페이지를 표시하기 수월해질듯 합니다.

**Comment by jis-kim** [comment]
total : number 형식으로 드리겠습니다~
