### ISSUE TITLE
🐛 [Bug] Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.

### ISSUE THREAD

**Issue by nyeoni** [GhostPangPang/GhostPong#246]
### Problem

백엔드의 `enableCors` 하는 과정에서 `content-type` 헤더에 대한 접근권한이 없어 발생하는 문제로 보임

### Reproduction

클라이언트에서 `post` 요청시 발생

### Screenshot

<img width="548" alt="image" src="https://github.com/GhostPangPang/GhostPong/assets/51353146/416ec188-2b26-467f-b3a4-3320ed6eaf54">

### Expected Behavior

- 에러 X

### Log

```Shell
cess to XMLHttpRequest at 'http://localhost:3000/user' from origin 'http://localhost:5173' has been blocked by CORS policy: Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.
```

### Browser

Chrome

**Comment by jis-kim** [comment]
지금 #243 이슈 처리중인데 같이 해결하도록 하겠습니다! 어떤 요청에서 난 에러인지 알려주실 수 있나요?

**Comment by aLVINlEE9** [comment]
<img width="791" alt="image" src="https://github.com/GhostPangPang/GhostPong/assets/74805318/58d2a0e3-d6ae-4b30-aff4-f2a51b872994">

<img width="791" alt="image" src="https://github.com/GhostPangPang/GhostPong/assets/74805318/a5eb768f-bae8-49d7-8eb9-088fad444133">
