### ISSUE TITLE
🐛 [Bug] 유저 닉네임 변경 , 닉네임 초기 설정  API 리스폰스 오류

### ISSUE THREAD

**Issue by aLVINlEE9** [GhostPangPang/GhostPong#306]
### Problem

{
  message: 'message'
}

형식으로 오지 않습니다. 확인 부탁드릴게여

### Reproduction

<img width="625" alt="image" src="https://github.com/GhostPangPang/GhostPong/assets/74805318/f12108d1-37ea-44f2-95c2-e403d6b40847">

**Comment by Kimhan-nah** [comment]
닉네임 초기 설정은 redirect 되기 때문에 `response를` 보내지 않고,
닉네임 변경은 `response` message로 수정!
