### ISSUE TITLE
📝 [Docs] nest.js app 실행 방법

### ISSUE THREAD

**Issue by jis-kim** [GhostPangPang/GhostPong#36]
## nest.js app 초기 실행
backend 디렉토리 안에서 실행해주세요.
- `.env.sample` 파일 참고해서 `.env` 파일 작성
  - db host 와 app url은 일단 "localhost" 로 작성해주세요
- `yarn install`
- `yarn db`
- `psql -U [username] -d [dbname] -h [dbhost] -p [dbport] -f ../database/create-table.sql`
  - psql 은 설치가 필요할 수 있습니다. `brew install libpq`
- `yarn start:prod` 또는 `yarn start:dev`
  - `yarn start:prod` : NODE_ENV=production 환경변수 설정해서 클라이언트가 `Authorization` header로 'token' 담아서 통신할 때 사용
  - `yarn start:dev` : NODE_ENV=development 환경변수 설정해서 클라이언트가 `x-my-id` header로 'user id' 담아서 통신할 때 사용

## DB 테이블이 존재하는 상태에서 실행
- psql 실행 없이 `yarn db` 후 바로 `yarn run start` 해주시면 됩니다.
- `yarn db:reset` 으로 볼륨을 삭제하고 다시 초기 실행할 수도 있습니다.

## DB seeding
- `.env` 파일에 `TEST_DB_NAME` 설정 되었는지 확인합니다. (해당 환경변수를 읽어서 실행합니다.)
- `yarn seed:reset && yarn seed [number]`
  - `yarn seed:reset` 시 테스트 데이터베이스가 날아갔다가 다시 생성되므로 사용에 주의해주세요!
  - `[number]` 자리에는 생성하고자 하는 `auth` 의 row 수를 입력합니다. 확률에 따라 `user`, `friendship`, `message` 가 차례로 생성됩니다.
  - 생성된 데이터는 `backend/seeding/results/[table명].json` 에서 파일로 확인 가능합니다.
 
- 실행 결과
  <img width="646" alt="Screenshot 2023-04-18 at 6 48 13 PM" src="https://user-images.githubusercontent.com/71019735/232765816-501dd141-2461-42f1-9c23-9adb77f81fc7.png">
- auth
  <img width="551" alt="Screenshot 2023-04-18 at 8 42 15 PM" src="https://user-images.githubusercontent.com/71019735/232766484-f7f17b29-8419-4b6a-af72-b84c52de8110.png">
- user
  <img width="486" alt="Screenshot 2023-04-18 at 8 42 57 PM" src="https://user-images.githubusercontent.com/71019735/232766666-dc55dbfb-da5a-4a1d-9249-183546fe0111.png">
- friend
  <img width="553" alt="Screenshot 2023-04-18 at 8 52 08 PM" src="https://user-images.githubusercontent.com/71019735/232768678-8de48cde-aea4-4732-9769-7093cbe010e7.png">
- message
  <img width="1195" alt="Screenshot 2023-04-18 at 8 51 38 PM" src="https://user-images.githubusercontent.com/71019735/232768573-784bfa73-143c-4aab-8821-83c68702487f.png">

## Swagger
-  nest app 실행해주시고 `localhost:${APP_PORT}/api` 로 접속하시면 swagger 로 테스트 하실 수 있습니다.

**Comment by nyeoni** [comment]
`brew install psql` 이 아닌 `brew install libpq` 인 것 같습니다. 이 부분 수정해주시면 감사하겠습니당 :)

저는 아래 순서로 설치 진행하였습니다
```
brew install libpq
echo 'export PATH="/usr/local/opt/libpq/bin:$PATH"' >> ~/.zshrc
source ~/.zshrc
```

**Comment by Kimhan-nah** [comment]
`psql -U [username] -d [dbname] -h [dbhost] -f ../database/create-table.sql` 에서
`psql -U [username] -d [dbname] -h [dbhost] -p [dbport] -f ../database/create-table.sql` 로 수정 필요할 거 같아요 🤓

**Comment by jis-kim** [comment]
@Kimhan-nah 수정하겠습니다 고맙습니다~! 저는 로컬에서 실행하다보니 놓친점이 꽤 많네요
