### ISSUE TITLE
🐛 [Bug] Channel list 에서 뒤로가기 했을 때 alert 

### ISSUE THREAD

**Issue by jis-kim** [GhostPangPang/GhostPong#420]
### Problem

채널 리스트에서 채널에 한 번 들어갔다가 뒤로 가기 하면 해당 alert 가 뜨는데 또 뒤로가기를 하면 (/channel/list 에서 뒤로가기) 또 같은 alert 가 뜹니다.
그냥 채널 리스트에서 뒤로가기 하면 괜찮습니다.

### Reproduction

채널 리스트 보기 -> 채널 만들기 혹은 입장 -> 뒤로가기 -> 뒤로가기

### Screenshot

<img width="1376" alt="Screenshot 2023-05-24 at 9 50 14 PM" src="https://github.com/GhostPangPang/GhostPong/assets/71019735/b97b5581-17cd-4d98-88eb-e97d395f079d">

`leave-channel` 이 계속 요청되는 것으로 보입니다. console 에는 해당 이벤트에서 일어나는 exception 의 메세지가 발생합니다.
<img width="691" alt="Screenshot 2023-05-24 at 9 54 33 PM" src="https://github.com/GhostPangPang/GhostPong/assets/71019735/a2062c45-3299-48aa-ab59-34d5fe4d5375">

### Log

```Shell
WebSocket Error {status: 'error', message: 'channelId must be longer than or equal to 21 characters'}message: "channelId must be longer than or equal to 21 characters"status: "error"[[Prototype]]: Object
SocketHandler.tsx:63
```

### Browser

Chrome

**Comment by aLVINlEE9** [comment]
해결된 PR 올라가있습니당
