### ISSUE TITLE
🔨 [Refactoring] 모든 api 앞에 prefix 추가하기

### ISSUE THREAD

**Issue by Kimhan-nah** [GhostPangPang/GhostPong#434]
### Description

- 모든 api 앞에 prefix 추가 필요
- global prefix 설정하기 (`/api/v1/`)

### Todo
- [ ] app controller에서 필요없는 코드 삭제하기

**Comment by jis-kim** [comment]
https://docs.nestjs.com/faq/global-prefix
참고하세요~
