### ISSUE TITLE
🐛 [Bug] 방장이 채널을 나갔다가 다시 와서 방장하면 게임시 공이 안생김

### ISSUE THREAD

**Issue by anso33** [GhostPangPang/GhostPong#483]
### Problem

게임 시작했는데 공이 안생겨요ㅜㅠ

### Reproduction

1. A가 채널을 생성한다. A가 방장
2. B가 채널에 참여한다. 
3. A와 B가 게임을 한다. 
4. 게임이 끝났을 때 A가 (채널) 나가기를 누른다.
5. A가 다시 해당 채널에 들어간다.
(이때 B의 페이지에 갑자기 이전에 했던 game result 페이지가 나온다.)
6. A가 방장에 참여한다. 
7. A가 다시 게임을 시작한다. 
(이때 A와 B의 페이지에 갑자기 이전에 했던 game result 페이지가 다시 나온다.)
8 공이 처음 한번 나와서 승패가 갈린다. 

다음으로 공이 안나옴....

### Screenshot

<img width="845" alt="image" src="https://github.com/GhostPangPang/GhostPong/assets/68376744/905e6064-6df7-4220-ac5a-9a29b9bc31ab">

**Comment by jis-kim** [comment]
게임 종료후 채널로 돌아갔을 땨 겟 채널 api 다시 호출해야함

**Comment by nyeoni** [comment]
54321
