### ISSUE TITLE
🐛 [Bug] player bar 위로 가는 문제

### ISSUE THREAD

**Issue by jis-kim** [GhostPangPang/GhostPong#487]
### Problem

- player 의 바를 위로 끝까지 올렸을 때 벽을 뚫고 나가는 현상
- client, server 모두 처리가 필요함
- [x] #522

### Reproduction

- 바를 위로 끝까지 올려보십시오

**Comment by anso33** [comment]
이거 버그였어요? 난 바의 중심점이 기준이라 그런줄ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
