### ISSUE TITLE
🐛 [Bug] Svg 이미지 정적파일로 변경 or 리액트 컴포넌트로 변경하기

### ISSUE THREAD

**Issue by nyeoni** [GhostPangPang/GhostPong#499]
### Problem

Svg 이미지 정적파일로 변경 or 리액트 컴포넌트로 변경하기
- `svg` 이미지를 사용하고 있는 부분에서 `image` src 면 정적파일경로로 수정
- 그 외에는 리액트 컴포넌트로 수정

### Reproduction

- svg 이미지 사용하고 있는 부분

### Screenshot

<img width="1792" alt="image" src="https://github.com/GhostPangPang/GhostPong/assets/51353146/dc020433-47df-45f9-bda3-1e06e98c27c3">

**Comment by aLVINlEE9** [comment]
해결되었습니다!
