### ISSUE TITLE
🐛 [Bug] 새로 로그인해서 닉네임 설정했는데 로비페이지로 안넘어가요

### ISSUE THREAD

**Issue by anso33** [GhostPangPang/GhostPong#500]
### Problem

새로 로그인해서 닉네임설정했는데 로비페이지로 안넘어가요.

### Reproduction

1. 새로운 유저가 로그인을 누른다.
2. 42auth하고 돌아와서 닉네임 친다.
3. 닉네임 넣는 칸 아래 start버튼을 누른다. 
-> 근데 아무일도 안일어난다. (페이지가 안넘어감)

-> 그런데 내 계정이 생성되어 있음.

**Comment by Kimhan-nah** [comment]
#503 해결되었습니다
