### ISSUE TITLE
🐛 [Bug] 바보 모드 게임에서 포커싱된 유저의 바만 크게 보여요

### ISSUE THREAD

**Issue by anso33** [GhostPangPang/GhostPong#511]
### Problem

🐛 [Bug] 바보 모드 게임에서 포커싱된 유저(나)의 바만 크게 보여요

### Reproduction

바보 모드로 게임을 하면 나의 바는 일반 모드의 바와 크기가 동일하고 상대방의 바는 더 짧아보여요.

### Screenshot

<img width="1502" alt="image" src="https://github.com/GhostPangPang/GhostPong/assets/68376744/d270f83d-a050-4bf2-843d-4fe2aa530f05">

**Comment by chichoon** [comment]
이거짱웃기다 ㅋㅋㅋㅋ̄̈ㅋ꙼̈ㅋ̆̎ㅋ̐̈ㅋ̊̈ㅋ꙼̈ㅋ̆̎ㅋ̐̈ㅋ̊̈ㅋ꙼̈ㅋ̆̎ㅋ̐̈ㅋ̊̈
