### ISSUE TITLE
🐛 [Bug] ban 당했을 때 메세지 워딩 변경

### ISSUE THREAD

**Issue by jis-kim** [GhostPangPang/GhostPong#513]
### Problem

ban 인데 차단당했다고 나와요~

### Reproduction

ban 당했을 경우, ban 당한 방에 입장할 경우 

### Screenshot

<img width="1130" alt="Screen Shot 2023-05-29 at 12 32 16 AM" src="https://github.com/GhostPangPang/GhostPong/assets/71019735/5ed5df5b-8380-4da4-8f52-cebd7567756a">
<img width="1067" alt="Screen Shot 2023-05-29 at 12 30 48 AM" src="https://github.com/GhostPangPang/GhostPong/assets/71019735/51ddb3c5-544d-48d8-8a72-951f85798953">

**Comment by aLVINlEE9** [comment]
해결되었습니다
