### ISSUE TITLE
🐛 [Bug] 채널 안 채팅 고쳐주세요

### ISSUE THREAD

**Issue by anso33** [GhostPangPang/GhostPong#515]
### Problem

채널 안에서 채팅할 때 너무 많은 글자(512)넘으면 안보내져요. 프론트에서도 내 창에 안그려지게 고쳐주세요.
글자수가 화면보다 많으면 좌측이 뚫려요. 보내는 사람 이름이 안보여요...
그런데 우측도 사진과 같이 뚫리긴 합니다. 

### Reproduction

채팅하기

### Screenshot

<img width="2367" alt="image" src="https://github.com/GhostPangPang/GhostPong/assets/68376744/1ae7da59-71de-4478-8696-d78bf654ee34">

**Comment by aLVINlEE9** [comment]
해결되었습니다!
