### ISSUE TITLE
🐛 [Bug] 유저 히스토리 api 1으로 고정되어서 요청

### ISSUE THREAD

**Issue by jis-kim** [GhostPangPang/GhostPong#517]
### Problem

- profile 페이지 접속했을 때 history 가 항상 id 1 인 유저의 히스토리로 나타남.

### Reproduction

- 1이 아닌 유저의 프로필 조회

### Screenshot

<img width="2125" alt="Screen Shot 2023-05-29 at 1 07 08 AM" src="https://github.com/GhostPangPang/GhostPong/assets/71019735/78ca84a4-e5ab-4ee3-8d3b-a4fa3f2ba9d2">

### Expected Behavior

/profile/2 면 2, 3이면 3의 history 가 떠야합니다.

**Comment by aLVINlEE9** [comment]
해결되었습니다!
