### ISSUE TITLE
🐛 [Bug] 채널에서 친구 리스트가 mocking data

### ISSUE THREAD

**Issue by jis-kim** [GhostPangPang/GhostPong#520]
### Problem

친구를 초대하고 싶어요......

### Reproduction

채널에서 친구 토글 누르기

### Screenshot

<img width="2207" alt="Screen Shot 2023-05-29 at 1 26 50 AM" src="https://github.com/GhostPangPang/GhostPong/assets/71019735/7098e77e-fc79-4d55-88ce-eac5c996dabe">

**Comment by aLVINlEE9** [comment]
친구 초대하기 완성되면 될것입니다 조금만 기다려 주세용ㅎㅎㅎㅎㅎ

**Comment by aLVINlEE9** [comment]
해결했어여
