### ISSUE TITLE
🔨 [Refactor] Game Layout Sidebar 

### ISSUE THREAD

**Issue by nyeoni** [GhostPangPang/GhostPong#523]
### Problem

GameLayout 안의  Sidebar 를 GameReadyPage 에만 있도록 빼주셨으면 좋겠습니다.
- random game 에서 사용하지 않음
- channel game 에서 사용하지 않음

### Reproduction

- 게임 페이지

**Comment by aLVINlEE9** [comment]
해결하였습니당
