### ISSUE TITLE
🐛 [Bug] 프로필 이미지 업로드 후 save하면 이미지가 깨집니다.

### ISSUE THREAD

**Issue by Kimhan-nah** [GhostPangPang/GhostPong#527]
### Problem

디폴트 이미지와 프로필 이미지 업로드 직후까지는 이미지가 잘 보이다가 'save' 하면 이미지가 깨집니다

### Reproduction

뭔가.. 서버에서 받아오는 이미지 경로가 잘못 되었거나...흠... 서버에 갔다오면 깨지는 거 같아요
user info 가져오면서 깨지는 것 같습니다

### Screenshot

![image](https://github.com/GhostPangPang/GhostPong/assets/33301153/f6fdf4e2-ff38-45f6-a575-ae45c41404b2)
<img width="716" alt="스크린샷 2023-05-29 오후 1 07 41" src="https://github.com/GhostPangPang/GhostPong/assets/33301153/5b6b628b-2630-429d-85ac-9dd8a573b224">

**Comment by jis-kim** [comment]
nginx proxy pass 설정으로 해결했습니다. docker-file 브랜치에 합쳐서 push 하겠습니다!
