### ISSUE TITLE
🐛 [Bug] 채널 안의 채팅 창에 남아있는 버그들

### ISSUE THREAD

**Issue by anso33** [GhostPangPang/GhostPong#528]
### Problem

- 한글은 괜찮은데 영어로 길게 치면 채팅창이 가로로 늘어납니다. 
- 영어로 512자 넘게 쳤는데 나에게 채팅이 그려집니다. 그려지지 않게 처리해주세요.

### Reproduction

채팅창에 영어로 많-이 치면 됩니다.

### Screenshot

<img width="1567" alt="image" src="https://github.com/GhostPangPang/GhostPong/assets/68376744/42680762-387b-41eb-a9e1-32f162d93e19">

**Comment by anso33** [comment]
@aLVINlEE9  이것은 고쳐야할 것 같아요. 응급은 아닌데 넘어갈건 아닌 것 같습니당

**Comment by aLVINlEE9** [comment]
해결했습니다
