### ISSUE TITLE
🔨 [Refactoring] channel-invited 이벤트에 ChannelId가 있었으면 좋겠습니다. 

### ISSUE THREAD

**Issue by aLVINlEE9** [GhostPangPang/GhostPong#532]
### Description

channel-invited 이벤트에 ChannelId가 있었으면 좋겠습니다. 
지금은 user nickname밖에 안와영

### Todo

- [ ] todo1

**Comment by jis-kim** [comment]
#537  로 해결되어서 닫겠습니다.
