### ISSUE TITLE
🐛 [Bug] 랜덤 게임 페이지에 나가기 버튼이 없어요

### ISSUE THREAD

**Issue by anso33** [GhostPangPang/GhostPong#538]
### Problem

랜덤 게임 페이지에 나가기 버튼이 없어요

### Reproduction

말 그대롭니다ㅎ

### Screenshot

<img width="1315" alt="image" src="https://github.com/GhostPangPang/GhostPong/assets/68376744/31537234-2328-43ac-b451-ca481b22aa12">

**Comment by jis-kim** [comment]
게임탈출절.대.안.돼

**Comment by nyeoni** [comment]
게임에서 나가기버튼은 없는 것이 맞습니다. :)!!!!!
