### ISSUE TITLE
🐛 [Bug] 뒤로가기 이슈

### ISSUE THREAD

**Issue by jis-kim** [GhostPangPang/GhostPong#539]
### Problem

앞으로가기를 해도 뒤로가시겠습니까? 창이 뜹니다.
뒤로가시겠습니까? 에서 esc 를 눌러도 뒤로가집니다. 뒤로안가져야 할 것 같아요.
취소를 눌러도 뒤로가집니다........
모든 route 에서 뒤로가기를 하면 뒤로가시겠습니까? 창이 뜨는데 이것은 의도하신 동작인지 궁금합니다.

### Reproduction

아무튼 뒤로가기, 앞으로가기를 해보면 됨

**Comment by aLVINlEE9** [comment]
해결했어영
