### ISSUE TITLE
🐛 [Bug] 플레이어되기 alert 없애주세요

### ISSUE THREAD

**Issue by nyeoni** [GhostPangPang/GhostPong#544]
### Problem

- 유저가 관전자에서 플레이어가 되었을 때 `alert` 하는 로직을 없애야합니다.
- 채널 정보 업데이트가 늦습니다.

### Reproduction

- 플레이어 되기를 누르면 됩니다. 

### Screenshot

<img width="952" alt="image" src="https://github.com/GhostPangPang/GhostPong/assets/51353146/33eb0b45-f60e-441f-a1b8-d3e4dee8d870">

**Comment by aLVINlEE9** [comment]
해결했어영
