### ISSUE TITLE
🐛 [Bug] 로그아웃 전에 채널 나가진다는 alert 창 띄워주세요

### ISSUE THREAD

**Issue by Kimhan-nah** [GhostPangPang/GhostPong#552]
### Problem

- 로그아웃할 때에도 채널에 나가진다는 alert 창이 필요할 것 같습니다

### Reproduction

- 뒤로가기 동작과 동일하게 alert 띄워준 후 로그아웃 처리되게 해주세용

**Comment by nyeoni** [comment]
채널에서 로그아웃 못하는데용??!!!@
