### ISSUE TITLE
🐛 [Bug] 랜덤게임에서 game result가 꺼지고 난 뒤 게임 페이지에 계속 머물러 있어요

### ISSUE THREAD

**Issue by anso33** [GhostPangPang/GhostPong#560]
### Problem

랜덤게임에서 승패가 갈리고 난 뒤 game result가 5초동안 보이고 나면 로비페이지같은데로 안돌아가고 게임페이지가 유지되고 있어요

### Reproduction

.

### Screenshot

<img width="1717" alt="image" src="https://github.com/GhostPangPang/GhostPong/assets/68376744/acc91c82-f88a-48d6-8e8f-7ad33dbee12a">

**Comment by nyeoni** [comment]
우왓 이슈 레포트 감사합니다!!
