### ISSUE TITLE
🐛 [Bug] 유저 경험치 업데이트가 안 돼요

### ISSUE THREAD

**Issue by Kimhan-nah** [GhostPangPang/GhostPong#579]
### Problem
헤더에 유저 경험치가 0으로 고정되어 있습니다
DB와 Response의 exp 확인해보면 6입니다!

### Reproduction

response에 exp 값에 맞는 경험치로 보이게 해주세용!

### Screenshot

<img width="608" alt="스크린샷 2023-07-14 오후 3 48 42" src="https://github.com/GhostPangPang/GhostPong/assets/33301153/f05a3ea7-2a35-4ec6-bbaf-512191364e49">

**Comment by nyeoni** [comment]
오늘 뷰 테스트 해본 결과 react-query 캐싱 문제인듯 하네요
