### ISSUE TITLE
🐛 [Bug] yarn seed 가 안돼요

### ISSUE THREAD

**Issue by nyeoni** [GhostPangPang/GhostPong#584]
### Problem

`yarn db` 를 한 후 `yarn seed 20` 을 하면 에러가 납니다.
`yarn start:dev` 를 하면 에더가 납니다. 

### Reproduction

- `yarn seed 20`
- `yarn start:dev`

### Screenshot

- `yarn seed **`
<img width="477" alt="image" src="https://github.com/GhostPangPang/GhostPong/assets/51353146/88a15aea-a136-4dc8-a0da-74a6e1e0fa6e">

- `yarn start:dev`
<img width="472" alt="image" src="https://github.com/GhostPangPang/GhostPong/assets/51353146/38041429-2ab0-4be3-a6d7-58bad1626d21">

### Expected Behavior

local 모드에서 실행할 수 있어야 합니다.

**Comment by jis-kim** [comment]
`env` 파일의 `DB_HOST` 가 'ghostgres' 로 지정되어있어서 나는 오류입니다! 당장 실행하시려면 백엔드 `env` 파일의 `DB_PORT` 를 8000 으로, `DB_HOST` 를 `localhost` 로 지정해주시면 됩니다!
dev 의 env 분리하는 방식으로 해결해서 pr 하겠습니다.
