### ISSUE TITLE
🐛 [Bug] InternalOAuthError 로그인 에러

### ISSUE THREAD

**Issue by Kimhan-nah** [GhostPangPang/GhostPong#601]
### Problem

- 42 로그인 시도하면 `InternalOAuthError` 발생 (나만)
- 정상적으로 동작하는 env 파일을 동일하게 사용했는데 에러 당하는중....

### Reproduction

- 모르겠어요..

### Screenshot

<img width="785" alt="스크린샷 2023-08-12 오후 5 27 21" src="https://github.com/GhostPangPang/GhostPong/assets/33301153/59a9f8c6-6e33-48ff-bd1f-efb63bafec95">

**Comment by jis-kim** [comment]
런타임에서 42 env 찍어봤을 때 제대로 나오나요...?

**Comment by Kimhan-nah** [comment]
### 에러 설명
![image](https://github.com/GhostPangPang/GhostPong/assets/33301153/9cef2fc3-be17-4e3f-96a1-8f61c6240c38)
"Error: unable to get local issuer certificate"라는 메세지와 함께 `UNABLE_TO_GET_ISSUER_CERT_LOCALLY` 라는 SSL 인증서 관련 에러가 발생했습니다.

### 해결방법
`yarn config set cafile /etc/ssl/cert.pem`으로 CA file 경로를 지정해서 해결했습니다..!
